site_name: WebNR - Web Novel Reader
site_description: A modern, privacy-focused, cross-platform web novel reader
site_url: https://www.webnovel.win
repo_url: https://github.com/yunwei37/webNR
repo_name: webNR

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables

plugins:
  - search
  - blog
  - social
  - rss:
      match_path: ".*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors  
  # - i18n:
  #     docs_structure: suffix
  #     default_language: en
  #     languages:
  #       - locale: en
  #         default: true
  #         name: English
  #         build: true
  #       - locale: zh
  #         name: Chinese
  #         build: true

extra:
  analytics:
    provider: google
    property: G-DGH8HNQKE4
  # alternate:
  #   - name: English
  #     link: /
  #     lang: en
  #   - name: 中文
  #     link: /zh/
  #     lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yunwei37/webNR
    - icon: fontawesome/solid/house
      link: https://webnovel.win

copyright: Copyright &copy; 2024 WebNR
